CREATE TABLE IF NOT EXISTS ENTITY
(
    id INT PRIMARY KEY AUTO_INCREMENT,
    attribute VARCHAR(45) NOT NULL
);

CREATE TABLE IF NOT EXISTS USER_DETAILS
(
    username VARCHAR(40) PRIMARY KEY,
    password VARCHAR(40) DEFAULT '123456' NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS unique_index ON USER_DETAILS (username);

CREATE TABLE IF NOT EXISTS USER_AUTH
(
    username VARCHAR(40) NOT NULL,
    authority VARCHAR(40) NOT NULL,
    CONSTRAINT FK_USERNAME FOREIGN KEY (username) REFERENCES USER_DETAILS (username)
);

CREATE INDEX IF NOT EXISTS FK_USERNAME_IDX ON USER_AUTH (username);